version: '3.8'

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: "18.216.27.57"
      KC_DB_USERNAME: application
      KC_DB_PASSWORD: cisvo0-Foczac-pyscak
      KC_HTTP_PORT: 8100
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: "keycloak.dev.careviah.com"
      KC_PROXY_HEADERS: "xforwarded"
      KC_PROXY: "edge"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"      
      
    ports:
      - "8100:8100"
    depends_on:
      - keycloak-db
    volumes:
      - ./themes:/opt/keycloak/themes

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: